config/routes.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap" => "cms_site#sitemap", :defaults => {:format => :xml}

match 'site/login', :to => 'cms_site#login', :as => 'cms_login', :via => [:get, :post]
match 'site/logout', :to => 'cms_site#logout', :as => 'cms_logout', :via => [:get, :post]
match 'site/register', :to => 'cms_site#register', :via => [:get, :post], :as => 'cms_register'
match 'site/lost_password', :to => 'cms_site#lost_password', :via => [:get, :post], :as => 'cms_lost_password'
match 'site/activate', :to => 'cms_site#activate', :via => :get
match 'site/expire_cache', :to => 'cms_site#expire_cache', :via => :get, :as => 'site_expire_cache'
match 'auto_completes/cms_page_tags' => 'auto_completes#cms_page_tags', :via => :get, :as => 'auto_complete_cms_page_tags'

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"
get 'cms_menus/parent_menu_options' => 'cms_menus#parent_menu_options'

scope '/cms' do
  resources :cms_pages, :path => 'pages' do
    member do
     get :preview
     get :expire_cache
    end
    collection do
      get :search
    end
  end
  resources :cms_parts, :path => 'parts' do
    member do
     get :expire_cache
     get :preview
    end
  end
  resources :cms_snippets, :path => 'snippets' do
    member do
      get :preview
    end
  end
  resources :cms_variables, :path => 'variables'
  resources :cms_layouts, :path => 'layouts' do
    member do
      get :preview
    end
  end
  resources :cms_assets, :path => 'assets', :except => [:edit, :update, :show]
  resources :cms_redmine_layouts, :path => 'redmine_layouts'
  resources :cms_menus, :path => 'menus'
  resources :cms_redirects, :path => 'redirects'
  resources :cms_settings, :path => 'settings' do
    collection do
      get 'redmine_hooks'
      post 'save'
    end
  end
  get "/:object_type/:id/history" => "cms_history#history", :as => "cms_object_history"
  get "/:object_type/:id/diff" => "cms_history#diff", :as => "cms_object_diff"
  get "/:object_type/:id/annotate" => "cms_history#annotate", :as => "cms_object_annotate"
  get 'assets/:id/(:filename)', :to => 'cms_assets#show', :id => /\d+/, :filename => /.*/, :as => 'named_asset'
  get 'assets/download/:id/:filename', :to => 'cms_assets#download', :id => /\d+/, :filename => /.*/, :as => 'download_named_asset'
  get 'assets/download/:id', :to => 'cms_assets#download', :id => /\d+/, :as => 'download_cms_asset'
  get 'assets/thumbnail/:id/:size/:filename', :to => 'cms_assets#thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+|\d+x\d+/, :as => 'cms_thumbnail'
  get 'assets/timelink/:id/:timestamp/:key/:filename', :to => 'cms_assets#timelink', :id => /\d+/, :filename => /.*/, :timestamp => /\d+/, :key => /([0-9a-f]{32})/, :as => 'cms_timelink'
  get 'assets/edit', :to => 'cms_assets#edit', :as => :cms_assets_edit
  post 'assets', :to => 'cms_assets#update', :as => :cms_assets_update

  # Export
  get 'exports/:object_type/:id(.:format)' => 'cms_exports#new', :as => :cms_export
  post 'exports/:object_type/:id' => 'cms_exports#create'
  get 'exports/website' => 'cms_exports#website', :as => :cms_export_website
  post 'exports/website' => 'cms_exports#website'

  # Import
  get 'imports/website' => 'cms_imports#website', :as => :cms_import_website
  post 'imports/website' => 'cms_imports#website'
  get 'imports/:object_type' => 'cms_imports#new', :as => :cms_import
  post 'imports/:object_type' => 'cms_imports#create'

  # Voting
  get 'vote/:id' => 'cms_votes#vote', :as => :cms_page_vote
  resources :cms_page_queries
end

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/
get 'pages/:page_id/parts/*name' => 'cms_parts#show', :as => "show_site_part"

get 'pages/*path' => 'cms_pages#show', :as => "show_site_page"

app/models/cms_part.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsPart < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes
  include RedmineCms::Filterable

  belongs_to :page, class_name: 'CmsPage', foreign_key: 'page_id'

  acts_as_attachable_cms
  acts_as_versionable_cms
  Redmine::VERSION.to_s < '3.3' ?  acts_as_list(scope: :page_id) : acts_as_positioned(scope: :page_id)

  scope :active, lambda { where(:status_id => RedmineCms::STATUS_ACTIVE) }

  after_commit :touch_page

  validates_presence_of :name, :content, :page
  validates_format_of :name, :with => /\A(?!\d+$)[a-z0-9\-_]*\z/

  [:content, :header, :footer, :sidebar].each do |name, _params|
    src = <<-END_SRC
    def is_#{name}_type?
      self.name.strip.downcase == "#{name}"
    end
    END_SRC
    class_eval src, __FILE__, __LINE__
  end

  attr_protected :id if ActiveRecord::VERSION::MAJOR <= 4
  safe_attributes 'name',
                  'description',
                  'filter_id',
                  'status_id',
                  'page_id',
                  'position',
                  'is_cached',
                  'content'

  def copy_from(arg)
    part = arg.is_a?(CmsPart) ? arg : CmsPart.where(:id => arg).first
    self.attributes = part.attributes.dup.except('id', 'created_at', 'updated_at') if part
    self
  end

  def cache_key
    "#{ page.cache_key + '/' if page.present?}#{super}"
  end

  def active?
    self.status_id == RedmineCms::STATUS_ACTIVE
  end

  def to_s
    ERB::Util.html_escape(name)
  end

  def digest
    @generated_digest ||= digest!
  end

  def digest!
    Digest::MD5.hexdigest(content)
  end

  def title
    description.to_s.strip.blank? ? name : "#{description} (#{name})"
  end

  def self.find_part(*args)
    if args.first && args.first.is_a?(String) && !args.first.match(/^\d*$/)
      find_by_name(*args)
    else
      find(*args)
    end
  end

  def set_content_type(response)
    response.headers['Content-Type'] ||= filter.content_type.present? ? filter.content_type : 'text/html'
  end

  private

  def touch_page
    return unless page
    page.reload.touch
    page.expire_cache
  end
end

app/controllers/cms_parts_controller.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsPartsController < ApplicationController
  unloadable
  before_action :require_edit_permission, :except => [:show]
  before_action :find_part, :except => [:index, :new, :create, :show]
  before_action :find_page_part, :only => [:show]
  before_action :authorize_part, :only => [:show]
  before_action :require_admin, :only => :destroy

  helper :attachments
  helper :cms
  helper :cms_pages

  protect_from_forgery :except => :show

  def index
    redirect_to :controller => 'cms_pages', :action => 'index', :tab => 'parts'
  end

  def preview
    @current_version = @part.set_content_from_version(params[:version]) if params[:version]
    @page.listener = self
    @preview_content = @page.render_part(@part)
  end

  def show
    @page.listener = self
    render((Rails.version < '5.1' ? :text : :plain) => @page.render_part(@part), :layout => false)
  end

  def edit
    @current_version = @part.set_content_from_version(params[:version]) if params[:version]
  end

  def expire_cache
    Rails.cache.delete(@part)
    redirect_to :back
  end

  def new
    @part = CmsPart.new(:filter_id => 'textile', :page_id => params[:page_id])
    @part.copy_from(params[:copy_from]) if params[:copy_from]
  end

  def refresh
    expire_fragment(@part)
  end

  def update
    @part.safe_attributes = params[:part]
    @part.save_attachments(params[:attachments])
    if @part.save
      render_attachment_warning_if_needed(@part)
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html do
          redirect_back_or_default edit_cms_part_path(@part)
        end
        format.js do
          find_parts
          render :action => 'change'
        end
      end
    else
      render :action => 'edit'
    end
  end

  def create
    @part = CmsPart.new
    @part.safe_attributes = params[:part]
    @part.save_attachments(params[:attachments])
    if @part.save
      render_attachment_warning_if_needed(@part)
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'edit', :id => @part
    else
      render :action => 'new'
    end
  end

  def destroy
    if params[:version]
      version = @part.versions.where(:version => params[:version]).first
      if version.current_version?
        flash[:warning] = l(:label_cms_version_cannot_destroy_current)
      else
        version.destroy
      end
      redirect_to history_cms_part_path(@page)
    else
      @part.destroy
      redirect_to :controller => 'cms_pages', :action => 'edit', :tab => 'page_parts', :id => @page
    end
  end

  private

  def authorize_part
    deny_access unless @part.page.visible?
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_parts
    @page = @part.page
    @parts = @page.parts.order(:position)
  end

  def find_page_part
    @part = CmsPart.active.joins(:page).includes(:page => :attachments).where(:page_id => params[:page_id]).find_part(params[:id] || params[:name])
    raise ActiveRecord::RecordNotFound if @part.blank?
    @page = @part.page
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_part
    @part = CmsPart.includes(:page).find(params[:id])
    @page = @part.page
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def require_edit_permission
    deny_access unless RedmineCms.allow_edit?
  end
end

app/helpers/cms_parts_helper.rb
# encoding: utf-8
#
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

module CmsPartsHelper
  def change_part_status_link(part)
    url = {:controller => 'cms_parts', :action => 'update', :id => part, :part => params[:part], :status => params[:status], :tab => nil}

    if part.active?
      link_to l(:button_lock), url.merge(:part => {:status_id => RedmineCms::STATUS_LOCKED}, :unlock => true), :method => :put, :class => 'icon icon-lock'
    else
      link_to l(:button_unlock), url.merge(:part => {:status_id => RedmineCms::STATUS_ACTIVE}, :unlock => true), :method => :put, :class => 'icon icon-unlock'
    end
  end

  def parts_type_collection
    [["Pages", [["Content", "content"],
                ["Sections", "sections"],
                ["Sidebar", "sidebar"],
                ["Header", "header"],
                ["Footer", "footer"],
                ["Header tags", "header_tags"]]],
     ["Layout", [["Layout html head", "layout_html_head_part"],
                 ["Layout sidebar top", "layout_base_sidebar"],
                 ["Layout body top", "layout_body_top_part"],
                 ["Layout body bottom", "layout_body_bottom_part"]]]]
  end

  def parts_option_for_select
    parts = CmsPart.order(:part_type).where("#{CmsPart.table_name}.part_type NOT LIKE 'layout_%'").order(:content_type)
    return "" unless parts.any?
    previous_group = parts.first.part_type
    s = "<optgroup label=\"#{ERB::Util.html_escape(parts.first.part_type)}\">".html_safe
    parts.each do |part|
      if part.part_type != previous_group
        reset_cycle
        s << '</optgroup>'.html_safe
        s << "<optgroup label=\"#{ERB::Util.html_escape(part.part_type)}\">".html_safe
        previous_group = part.part_type
      end
      s << %Q(<option value="#{ERB::Util.html_escape(part.id)}">#{part.to_s}</option>).html_safe
    end
    s << '</optgroup>'.html_safe
    s.html_safe
  end
end

app/views/cms_parts/_form.html.erb
<%= error_messages_for 'part' %>

<div class="box tabular">

  <div class="splitcontent">
    <div class="splitcontentleft">
      <p><%= f.text_field :name, :size => 30, :required => true, :label => l(:label_cms_section)  %></p>
      <p><%= f.text_field :description, :size => "98%", :label => l(:label_cms_description)  %></p>

      <% if @part.new_record? || @part.page.blank?  %>
      <p>
        <%= f.select :page_id, pages_options_for_select(CmsPage.all), :required => true, :label => l(:label_cms_page) %>
      </p>
      <% end %>
      <p><%= f.select :status_id, cms_statuses_for_select, :label => l(:label_cms_status)  %></p>
    </div>
    <div class="splitcontentright">
      <p><%= f.check_box :is_cached, :label => l(:label_cms_is_cached) %></p>
      <p><%= f.select :filter_id, filter_options_for_select(@part.filter_id), {:label => l(:label_cms_filter)}, {:id => "text_filter_select", :onchange => "editor.setOption('mode', $('option:selected', this).data('mode'));return false"} %></p>
    </div>
  </div>


<!--
<p id="attachments_form"><label><%= l(:label_attachment_plural) %></label><%= render :partial => 'attachments/form', :locals => {:container => @part} %></p> -->

<%= text_area_tag 'part[content]', @part.content, :cols => 100, :rows =>  30, :class => 'wiki-edit' %>
<%= javascript_tag "editor = activateCodeMirror('part_content', '#{@part.filter.class.mine_type}');" %>
<%= javascript_tag "$('.contextual.page-edit').draggable();" %>

</div>

<%= javascript_tag do %>
  $(document).ready(function(){
    $('#part_page_id').select2({containerCssClass: "page-select icon icon-page"  });
  });
<% end %>

<% content_for :header_tags do %>
  <%= code_mirror_tags %>
  <%= javascript_include_tag 'redmine_cms', :plugin => 'redmine_cms'  %>
  <%= select2_assets %>
<% end %>

app/views/cms_parts/_parts.html.erb
<% if @parts.any? %>
  <table class="list page-parts">
    <thead>
      <tr>
        <th><%= l(:label_cms_name) %></th>
        <th><%= l(:label_cms_description) %></th>
        <th style="width:15%;"> </th>
      </tr>
    </thead>
    <tbody>
      <% @parts.each do |page_part| -%>
        <tr class="part <%= cycle("odd", "even") %>" id="page_part_<%= page_part.id %>">
          <td class="name"><%= link_to h(page_part.name), edit_cms_part_path(page_part) %></td>
          <td class="name"><%= link_to h(page_part.description), edit_cms_part_path(page_part) %></td>

          <td class="buttons">
            <%= stocked_reorder_link(page_part, 'part', { url: cms_part_path(page_part), param: 'part'}, :get) %>
            <%= cms_change_status_link('part', page_part) %>
            <%= link_to l(:label_history), cms_object_history_path(page_part, :object_type => page_part.class.name.underscore), :class => 'icon icon-history' if page_part.version > 1 %>
            <%= delete_link cms_part_path(page_part) if User.current.admin? %>
          </td>
        </tr>
      <% end -%>
  </tbody>
</table>
<%= javascript_tag do %>
  $(function() { $("table.page-parts tbody").positionedItems(); });
<% end %>
<% end %>

app/views/cms_parts/change.js.erb
$('#cms_page_parts').html('<%= escape_javascript(render :partial => 'cms_parts/parts') %>');

app/views/cms_parts/edit.html.erb
<div class="contextual">
  <%= link_to l(:label_cms_preview), preview_cms_part_path(@part), :class => 'icon icon-preview'  %>
  <%= link_to l(:label_cms_preview_page), preview_cms_page_path(@part.page), :class => 'icon icon-preview'  %>
  <%= link_to l(:label_history), cms_object_history_path(@part, :object_type => @part.class.name.underscore), :class => 'icon icon-history' %>
  <%= link_to l(:button_duplicate), new_cms_part_path(:copy_from => @part), :class => 'icon icon-duplicate' %>
  <%= delete_link cms_part_path(@part) if User.current.admin? %>
</div>


<h2><%= link_to l(:label_cms_page_plural), cms_pages_path %>
  <% @page.ancestors.each do |page| %>
    &#187; <%= link_to page.slug, edit_cms_page_url(page) %>
  <% end %>
    &#187; <%= @page.slug %>
</h2>

<div class="tabs part-tabs">
  <ul>
    <li><%= link_to(l(:label_cms_page), edit_cms_page_path(@part.page), :class => "page") %></li>
    <% @part.page.parts.active.order(:position).each do |part| %>
      <li><%= link_to(part.title, edit_cms_part_path(part), :class => "#{(@part.id == part.id ? 'selected' : nil)} #{'locked' unless part.active?}") %></li>
    <% end %>
    <li><%= link_to "+", new_cms_part_path(:page_id => @part.page.id) %></li>
  </ul>
  <div class="tabs-buttons" style="display:none;">
    <button class="tab-left" type="button" onclick="moveTabLeft(this);"></button>
    <button class="tab-right" type="button" onclick="moveTabRight(this);"></button>
  </div>
</div>

<%= labelled_form_for :part, @part, :url => { :action => 'update', :id => @part},
  :html => { :id => 'part_form', :multipart => true, :method => :put } do |f| %>

<%= render :partial => 'form', :locals => { :f => f } %>
<% if @page.attachments.any? %>
    <fieldset><legend><%= l(:label_attachment_plural) %></legend>
      <%= link_to_cms_attachments @page, :thumbnails => true  %>
    </fieldset>
    <br/>
  <% end %>

<!-- <fieldset><legend><%= l(:label_attachment_plural) %></legend>
  <%= link_to_cms_attachments @part, :thumbnails => true  %>
</fieldset><br/> -->

<% content_for :sidebar do %>
  <% render :partial => 'cms_settings/menu' %>
<% end %>

<%= submit_tag l(:button_save) %>
<%= link_to l(:label_cms_apply), "#", :style => "margin-left:10px;", :remote => true, :onclick => "editor.save(); $.ajax({url: '#{escape_javascript cms_part_path(@part)}', type: \'post\', dataType: \'script\', data: $(\'#part_form\').serialize()}); $('textarea').removeData('changed'); return false;"%>
<% end %>

<% content_for :header_tags do %>
  <div class="contextual page-edit" id="float_buttons">
    <%= link_to l(:label_cms_apply), "#", :remote => true, :onclick => "editor.save(); $.ajax({url: '#{escape_javascript cms_part_path(@part)}', type: \'post\', dataType: \'script\', data: $(\'#part_form\').serialize()}); $('textarea').removeData('changed'); return false;"%>
  </div>
<% end %>
<%= javascript_tag "$('.contextual.page-edit').draggable();" %>

<% html_title(@part.title + " " + @part.page.name) -%>

app/views/cms_parts/new.html.erb
<h2><%=l(:label_cms_part_new)%></h2>

<%= labelled_form_for :part, @part, :url => { :action => 'create', :project_id => @project },
  :html => { :id => 'part-form', :multipart => true }  do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>

<% content_for :header do %>
  <div class="contextual page-edit" id="float_buttons">
    <%= link_to l(:label_cms_apply), "#", :class => "icon icon-checked", :remote => true, :onclick => "editor.save(); $.ajax({url: '#{escape_javascript cms_parts_path(@part)}', type: \'post\', data: $(\'#part_form\').serialize()});return false;"%>
  </div>
<% end %>

<% html_title(l(:label_cms_part_new)) -%>

app/views/cms_parts/preview.html.erb
<h2><%= link_to cms_page_path(@part.page), edit_cms_page_url(@part.page, :tab => "page_parts") %>  &#187;  <%=l(:label_cms_part)%>: <%= @part.name + (@part.description.blank? ? '' : " (#{@part.description})") %></h2>

<div class="wiki page part <%= @part.name %>">
  <%= @preview_content %>
</div>

<% content_for :header_tags do %>
  <div class="contextual page-edit">
    <% if params[:version] && @part.version != @current_version %>
       <%= render :partial => 'cms_history/history_context_menu', :object => @part %>
    <% else %>
      <%= link_to l(:button_edit), edit_cms_part_path(@part), :class => 'icon icon-edit' %>
      <hr>
       <%= link_to l(:label_history), cms_object_history_path(@part, :object_type => @part.class.name.underscore), :class => 'icon icon-history'%>
      <hr>
      <%= link_to l(:label_cms_refresh_cache), expire_cache_cms_part_path(@part), :class => 'icon icon-reload' %>
    <% end %>
  </div>
  <%= javascript_tag "$('.contextual.page-edit').draggable();" %>
<% end if RedmineCms.allow_edit? %>