config/routes.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap" => "cms_site#sitemap", :defaults => {:format => :xml}

match 'site/login', :to => 'cms_site#login', :as => 'cms_login', :via => [:get, :post]
match 'site/logout', :to => 'cms_site#logout', :as => 'cms_logout', :via => [:get, :post]
match 'site/register', :to => 'cms_site#register', :via => [:get, :post], :as => 'cms_register'
match 'site/lost_password', :to => 'cms_site#lost_password', :via => [:get, :post], :as => 'cms_lost_password'
match 'site/activate', :to => 'cms_site#activate', :via => :get
match 'site/expire_cache', :to => 'cms_site#expire_cache', :via => :get, :as => 'site_expire_cache'
match 'auto_completes/cms_page_tags' => 'auto_completes#cms_page_tags', :via => :get, :as => 'auto_complete_cms_page_tags'

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"
get 'cms_menus/parent_menu_options' => 'cms_menus#parent_menu_options'

scope '/cms' do
  resources :cms_pages, :path => 'pages' do
    member do
     get :preview
     get :expire_cache
    end
    collection do
      get :search
    end
  end
  resources :cms_parts, :path => 'parts' do
    member do
     get :expire_cache
     get :preview
    end
  end
  resources :cms_snippets, :path => 'snippets' do
    member do
      get :preview
    end
  end
  resources :cms_variables, :path => 'variables'
  resources :cms_layouts, :path => 'layouts' do
    member do
      get :preview
    end
  end
  resources :cms_assets, :path => 'assets', :except => [:edit, :update, :show]
  resources :cms_redmine_layouts, :path => 'redmine_layouts'
  resources :cms_menus, :path => 'menus'
  resources :cms_redirects, :path => 'redirects'
  resources :cms_settings, :path => 'settings' do
    collection do
      get 'redmine_hooks'
      post 'save'
    end
  end
  get "/:object_type/:id/history" => "cms_history#history", :as => "cms_object_history"
  get "/:object_type/:id/diff" => "cms_history#diff", :as => "cms_object_diff"
  get "/:object_type/:id/annotate" => "cms_history#annotate", :as => "cms_object_annotate"
  get 'assets/:id/(:filename)', :to => 'cms_assets#show', :id => /\d+/, :filename => /.*/, :as => 'named_asset'
  get 'assets/download/:id/:filename', :to => 'cms_assets#download', :id => /\d+/, :filename => /.*/, :as => 'download_named_asset'
  get 'assets/download/:id', :to => 'cms_assets#download', :id => /\d+/, :as => 'download_cms_asset'
  get 'assets/thumbnail/:id/:size/:filename', :to => 'cms_assets#thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+|\d+x\d+/, :as => 'cms_thumbnail'
  get 'assets/timelink/:id/:timestamp/:key/:filename', :to => 'cms_assets#timelink', :id => /\d+/, :filename => /.*/, :timestamp => /\d+/, :key => /([0-9a-f]{32})/, :as => 'cms_timelink'
  get 'assets/edit', :to => 'cms_assets#edit', :as => :cms_assets_edit
  post 'assets', :to => 'cms_assets#update', :as => :cms_assets_update

  # Export
  get 'exports/:object_type/:id(.:format)' => 'cms_exports#new', :as => :cms_export
  post 'exports/:object_type/:id' => 'cms_exports#create'
  get 'exports/website' => 'cms_exports#website', :as => :cms_export_website
  post 'exports/website' => 'cms_exports#website'

  # Import
  get 'imports/website' => 'cms_imports#website', :as => :cms_import_website
  post 'imports/website' => 'cms_imports#website'
  get 'imports/:object_type' => 'cms_imports#new', :as => :cms_import
  post 'imports/:object_type' => 'cms_imports#create'

  # Voting
  get 'vote/:id' => 'cms_votes#vote', :as => :cms_page_vote
  resources :cms_page_queries
end

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/
get 'pages/:page_id/parts/*name' => 'cms_parts#show', :as => "show_site_part"

get 'pages/*path' => 'cms_pages#show', :as => "show_site_page"

app/controllers/cms_settings_controller.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsSettingsController < ApplicationController
  unloadable
  menu_item :cms_settings

  before_action :require_admin
  before_action :find_settings

  helper :cms

  def index
  end

  def redmine_hooks
  end

  def update
    params[:settings].each do |key, value|
      @settings[key] = value
    end
    Setting.plugin_redmine_cms = @settings
    flash[:notice] = l(:notice_successful_update)
    redirect_back_or_default :action => 'index', :tab => params[:tab]
  end

  def edit
  end

  def save
    find_project_by_project_id
    params_hash = params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params
    if params_hash[:cms_settings] && params_hash[:cms_settings].is_a?(Hash)
      settings = params_hash[:cms_settings]
      settings.map do |k, v|
        RedmineCms.set_project_settings(k, @project.id, v)
      end
    end
    redirect_to :controller => 'projects', :action => 'settings', :id => @project, :tab => params[:tab]
  end

  private

  def find_settings
    @settings = Setting.plugin_redmine_cms
    @settings = {} unless @settings.is_a?(Hash)
  end
end

app/views/cms_settings/_menu.html.erb
<div id="cms-settings-menu">
  <h3><%= l(:label_cms) %></h3>
  <ul>
    <li><%= link_to l(:label_settings), cms_settings_path, :class => "icon icon-settings #{'selected' if params[:controller] == 'cms_settings' && params[:action] == 'index'}" %></li>
    <li><%= link_to l(:label_cms_page_plural), cms_pages_path, :class => "icon icon-page #{'selected' if params[:controller] == 'cms_pages'}" %></li>
    <li><%= link_to l(:label_cms_snippet_plural), cms_snippets_path, :class => "icon icon-snippet #{'selected' if params[:controller] == 'cms_snipets'}" %></li>
    <li><%= link_to l(:label_cms_menu_plural), cms_menus_path, :class => "icon icon-menu #{'selected' if params[:controller] == 'cms_menus'}" %></li>
    <li><%= link_to l(:label_cms_layout_plural), cms_layouts_path, :class => "icon icon-layout #{'selected' if params[:controller] == 'cms_layouts'}" %></li>
    <li><%= link_to l(:label_cms_redmine_layout_plural), cms_redmine_layouts_path, :class => "icon icon-redmine-layout #{'selected' if params[:controller] == 'cms_redmine_layouts'}" %></li>
    <li><%= link_to l(:label_cms_redmine_hook_plural), redmine_hooks_cms_settings_path, :class => "icon icon-redmine-hooks #{'selected' if params[:controller] == 'cms_settings' && params[:action] == 'redmine_hooks'}" %></li>
    <li><%= link_to l(:label_cms_redirect_plural), cms_redirects_path, :class => "icon icon-redirect #{'selected' if params[:controller] == 'cms_redirects'}" %></li>
    <li><%= link_to l(:label_cms_asset_plural), cms_assets_path, :class => "icon icon-package #{'selected' if params[:controller] == 'cms_assets'}" %></li>
    <li><%= link_to l(:label_cms_variable_plural), cms_variables_path, :class => "icon icon-vars #{'selected' if params[:controller] == 'cms_variables'}" %></li>
  </ul>

  <h3><%= l(:label_cms_page_plural) %></h3>
  <%= render_page_jump_box %>

  <h3><%= l(:label_cms_page_tags) %></h3>
  <ul class="tags-cloud">

      <% CmsPage.tags_cloud.group_by { |tag| tag.name.downcase.first }.each do |letter, grouped_tags| %>
          <li class="letter"><%= letter.upcase %></li>
          <% grouped_tags.each do |tag| %>
            <li><%= render_cms_tag_link(tag, :show_count => true) %></li>
          <% end %>
      <% end %>
  </ul>

  <% if CmsPageQuery.visible.any? %>
    <h3><%= l(:label_cms_page_saved_queries) %></h3>
    <ul >
      <% CmsPageQuery.visible.find_each do |query| %>
        <li>
          <%= link_to(query.name, cms_pages_path(:query_id => query)) %>
        </li>
      <% end %>
    </ul>
  <% end %>

</div>

<% content_for :header_tags do %>
  <%= select2_assets %>
<% end %>

<%= javascript_tag do %>
  $(document).ready(function(){
    $('#page_quick_jump_box').select2({ width: '100%', containerCssClass: "page-select icon icon-page"  });
  });
<% end %>

app/views/cms_settings/index.html.erb
<% extend CmsPagesHelper %>
<% extend CmsHelper %>

<% html_title(l(:label_cms_settings)) -%>

<div class="contextual">
  <%= link_to l(:label_cms_refresh_cache), site_expire_cache_path, :class => 'icon icon-refresh' %>
  <%= link_to l(:label_cms_export_website), cms_export_website_path, :class => 'icon icon-save' %>
  <%= link_to l(:label_cms_import_website), cms_import_website_path, :class => 'icon icon-duplicate' %>
</div>

<h2><%= l(:label_cms_settings) %></h2>

<%= form_tag({:controller => :cms_settings, :action => :update, :id => '1', :tab => 'general'},
               :method => :put, :id => "cms_settings_form") do %>
<div class="box tabular">
  <p>
    <label for="use_localization"><%= l(:label_cms_use_localization) %></label>
    <%= hidden_field_tag 'settings[use_localization]', 0 %>
    <%= check_box_tag 'settings[use_localization]', 1, RedmineCms.use_localization?, :id => 'use_localization' %>
  </p>

  <p>
    <label><%= l(:label_cms_edit_permissions) %></label>
    <%= select_tag 'settings[edit_permissions]', cms_visibilities_for_select(@settings["edit_permissions"] || "admin", :only_groups => true, :admin => true)  %>
  </p>

  <p>
    <label><%= l(:label_cms_redmine_top_menu) %></label>
    <%= hidden_field_tag 'settings[show_home]', 0 %>
    <label class="block"><%= check_box_tag 'settings[show_home]', 1, @settings["show_home"].to_i > 0 %><%= l(:label_home) %></label>
    <%= hidden_field_tag 'settings[show_projects]', 0 %>
    <label class="block"><%= check_box_tag 'settings[show_projects]', 1, @settings["show_projects"].to_i > 0 %><%= l(:label_project_plural) %></label>
    <%= hidden_field_tag 'settings[show_help]', 0 %>
    <label class="block"><%= check_box_tag 'settings[show_help]', 1, @settings["show_help"].to_i > 0 %><%= l(:label_help) %></label>
  </p>

  <p>
    <label><%= l(:label_cms_cache_expires_in) %></label>
    <%= text_field_tag 'settings[cache_expires_in]', RedmineCms.cache_expires_in, :size => 5 %> <%= l(:label_cms_minute_plural) %>
  </p>

  <p>
    <label><%= l(:label_cms_use_public_urls) %></label>
    <%= hidden_field_tag 'settings[use_public_urls]', 0 %>
    <%= check_box_tag 'settings[use_public_urls]', 1, RedmineCms.use_public_urls?, :id => 'use_public_urls' %>
  </p>

  <p>
    <label><%= l(:label_cms_default_layout) %></label>
    <%= select_tag 'settings[default_layout]', options_for_select(cms_layouts_for_select, @settings["default_layout"]) %>
  </p>

  <% if CmsPage.any? %>
  <p>
    <label><%= l(:label_cms_landing_page) %></label>
    <%= select_tag 'settings[landing_page]', options_for_select(pages_options_for_select(CmsPage.all), @settings["landing_page"]), :include_blank => true %>
  </p>

  <p>
    <label><%= l(:label_cms_error_page) %></label>
    <%= select_tag 'settings[error_page]', options_for_select(pages_options_for_select(CmsPage.all), @settings["error_page"]), :include_blank => true %>
  </p>

  <% end %>

  <p>
    <label><%= l(:label_cms_default_fields) %></label>
    <%= text_field_tag 'settings[default_fields]', @settings["default_fields"] %>
    <br>
    <em class="info"><%= l(:text_comma_separated) %></em>
  </p>

</div>
<%= submit_tag l(:button_apply) %>
<% end %>

<% content_for :sidebar do %>
  <% render :partial => 'cms_settings/menu' %>
<% end %>

<% content_for :header_tags do %>
  <%= code_mirror_tags %>
  <%= javascript_include_tag 'redmine_cms', :plugin => 'redmine_cms'  %>
<% end %>

app/views/cms_settings/redmine_hooks.html.erb
<% extend CmsPagesHelper %>
<% extend CmsHelper %>

<% html_title(l(:label_cms_settings)) -%>

<h2><%= l(:label_cms_redmine_hook_plural) %></h2>

<%= form_tag({:controller => :cms_settings, :action => :update, :id => '1'},
               :method => :put, :id => "cms_settings_form") do %>
<%= hidden_field_tag :back_url, url_for(params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params) %>
<fieldset class="box"><legend>view_layouts_base_html_head</legend>
<%= text_area_tag 'settings[view_layouts_base_html_head_hook]', @settings["view_layouts_base_html_head_hook"], :class => 'wiki-edit', :rows => 5 %>
</fieldset>

<fieldset class="box"><legend>view_layouts_base_sidebar</legend>
<%= text_area_tag 'settings[view_layouts_base_sidebar_hook]', @settings["view_layouts_base_sidebar_hook"], :class => 'wiki-edit', :rows => 5 %>
</fieldset>

<fieldset class="box"><legend>view_layouts_base_body_bottom</legend>
<%= text_area_tag 'settings[view_layouts_base_body_bottom_hook]', @settings["view_layouts_base_body_bottom_hook"],:class => 'wiki-edit', :rows => 5 %>
</fieldset>



<%= submit_tag l(:button_apply) %>
<% end %>

<% content_for :sidebar do %>
  <% render :partial => 'cms_settings/menu' %>
<% end %>

<% content_for :header_tags do %>
  <%= code_mirror_tags %>
  <%= javascript_include_tag 'redmine_cms', :plugin => 'redmine_cms'  %>
<% end %>