config/routes.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap" => "cms_site#sitemap", :defaults => {:format => :xml}

match 'site/login', :to => 'cms_site#login', :as => 'cms_login', :via => [:get, :post]
match 'site/logout', :to => 'cms_site#logout', :as => 'cms_logout', :via => [:get, :post]
match 'site/register', :to => 'cms_site#register', :via => [:get, :post], :as => 'cms_register'
match 'site/lost_password', :to => 'cms_site#lost_password', :via => [:get, :post], :as => 'cms_lost_password'
match 'site/activate', :to => 'cms_site#activate', :via => :get
match 'site/expire_cache', :to => 'cms_site#expire_cache', :via => :get, :as => 'site_expire_cache'
match 'auto_completes/cms_page_tags' => 'auto_completes#cms_page_tags', :via => :get, :as => 'auto_complete_cms_page_tags'

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"
get 'cms_menus/parent_menu_options' => 'cms_menus#parent_menu_options'

scope '/cms' do
  resources :cms_pages, :path => 'pages' do
    member do
     get :preview
     get :expire_cache
    end
    collection do
      get :search
    end
  end
  resources :cms_parts, :path => 'parts' do
    member do
     get :expire_cache
     get :preview
    end
  end
  resources :cms_snippets, :path => 'snippets' do
    member do
      get :preview
    end
  end
  resources :cms_variables, :path => 'variables'
  resources :cms_layouts, :path => 'layouts' do
    member do
      get :preview
    end
  end
  resources :cms_assets, :path => 'assets', :except => [:edit, :update, :show]
  resources :cms_redmine_layouts, :path => 'redmine_layouts'
  resources :cms_menus, :path => 'menus'
  resources :cms_redirects, :path => 'redirects'
  resources :cms_settings, :path => 'settings' do
    collection do
      get 'redmine_hooks'
      post 'save'
    end
  end
  get "/:object_type/:id/history" => "cms_history#history", :as => "cms_object_history"
  get "/:object_type/:id/diff" => "cms_history#diff", :as => "cms_object_diff"
  get "/:object_type/:id/annotate" => "cms_history#annotate", :as => "cms_object_annotate"
  get 'assets/:id/(:filename)', :to => 'cms_assets#show', :id => /\d+/, :filename => /.*/, :as => 'named_asset'
  get 'assets/download/:id/:filename', :to => 'cms_assets#download', :id => /\d+/, :filename => /.*/, :as => 'download_named_asset'
  get 'assets/download/:id', :to => 'cms_assets#download', :id => /\d+/, :as => 'download_cms_asset'
  get 'assets/thumbnail/:id/:size/:filename', :to => 'cms_assets#thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+|\d+x\d+/, :as => 'cms_thumbnail'
  get 'assets/timelink/:id/:timestamp/:key/:filename', :to => 'cms_assets#timelink', :id => /\d+/, :filename => /.*/, :timestamp => /\d+/, :key => /([0-9a-f]{32})/, :as => 'cms_timelink'
  get 'assets/edit', :to => 'cms_assets#edit', :as => :cms_assets_edit
  post 'assets', :to => 'cms_assets#update', :as => :cms_assets_update

  # Export
  get 'exports/:object_type/:id(.:format)' => 'cms_exports#new', :as => :cms_export
  post 'exports/:object_type/:id' => 'cms_exports#create'
  get 'exports/website' => 'cms_exports#website', :as => :cms_export_website
  post 'exports/website' => 'cms_exports#website'

  # Import
  get 'imports/website' => 'cms_imports#website', :as => :cms_import_website
  post 'imports/website' => 'cms_imports#website'
  get 'imports/:object_type' => 'cms_imports#new', :as => :cms_import
  post 'imports/:object_type' => 'cms_imports#create'

  # Voting
  get 'vote/:id' => 'cms_votes#vote', :as => :cms_page_vote
  resources :cms_page_queries
end

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/
get 'pages/:page_id/parts/*name' => 'cms_parts#show', :as => "show_site_part"

get 'pages/*path' => 'cms_pages#show', :as => "show_site_page"

app/models/cms_snippet.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsSnippet < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes
  include RedmineCms::Filterable

  acts_as_attachable_cms
  acts_as_versionable_cms

  validates_presence_of :name, :content
  validates_format_of :name, :with => /\A(?!\d+$)[a-z0-9\-_]*\z/

  after_commit :expire_cache

  attr_protected :id if ActiveRecord::VERSION::MAJOR <= 4
  safe_attributes 'name',
                  'filter_id',
                  'description',
                  'content'

  def used_in_pages
    CmsPage.where("#{CmsPage.table_name}.content LIKE '%{% render_snippet '?' %}%'", name).order(:name)
  end

  def copy_from(arg)
    snippet = arg.is_a?(CmsSnippet) ? arg : CmsSnippet.where(:id => arg).first
    self.attributes = snippet.attributes.dup.except("id", "created_at", "updated_at") if snippet
    self
  end

  def digest
    @generated_digest ||= digest!
  end

  def digest!
    Digest::MD5.hexdigest(content)
  end

  def expire_cache
    used_in_pages.includes(:parts).map(&:expire_cache)
    CmsPage.joins(:layout).where("#{CmsLayout.table_name}.content LIKE '%{% render_snippet '?' %}%'", name).map(&:expire_cache)
  end
end

app/controllers/cms_snippets_controller.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsSnippetsController < ApplicationController
  unloadable
  before_action :require_edit_permission
  before_action :find_snippet, :except => [:index, :new, :create]

  helper :attachments
  helper :cms
  helper :cms_pages

  def index
    @snippets = CmsSnippet.order(:name)
  end

  def preview
    @current_version = @cms_snippet.set_content_from_version(params[:version]) if params[:version]
    page = CmsPage.new(:listener => self)
    @preview_content = page.render_part(@cms_snippet)
  end

  def edit
    @current_version = @cms_snippet.set_content_from_version(params[:version]) if params[:version]
  end

  def new
    @cms_snippet = CmsSnippet.new(:filter_id => 'textile')
    @cms_snippet.copy_from(params[:copy_from]) if params[:copy_from]
  end

  def update
    @cms_snippet.safe_attributes = params[:cms_snippet]
    @cms_snippet.save_attachments(params[:attachments])
    if @cms_snippet.save
      render_attachment_warning_if_needed(@cms_snippet)
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html { redirect_back_or_default edit_cms_snippet_path(@cms_snippet) }
      end
    else
      render :action => 'edit'
    end
  end

  def create
    @cms_snippet = CmsSnippet.new
    @cms_snippet.safe_attributes = params[:cms_snippet]
    @cms_snippet.save_attachments(params[:attachments])
    if @cms_snippet.save
      render_attachment_warning_if_needed(@cms_snippet)
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'edit', :id => @cms_snippet
    else
      render :action => 'new'
    end
  end

  def destroy
    if params[:version]
      version = @cms_snippet.versions.where(:version => params[:version]).first
      if version.current_version?
        flash[:warning] = l(:label_cms_version_cannot_destroy_current)
      else
        version.destroy
      end
      redirect_to history_cms_snippet_path(@page)
    else
      @cms_snippet.destroy
      redirect_to :controller => 'cms_snippets', :action => 'index'
    end
  end

  private

  def find_snippets
    @snippets = CmsSnippet.order(:name)
  end

  def find_snippet
    @cms_snippet = CmsSnippet.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def require_edit_permission
    deny_access unless RedmineCms.allow_edit?
  end
end

app/views/cms_snippets/_form.html.erb
<%= error_messages_for 'cms_snippet' %>

<div class="box tabular">

  <p><%= f.text_field :name, :size => 30, :required => true, :label => l(:label_cms_name)  %></p>
  <p><%= f.text_field :description, :size => "100%", :label => l(:label_cms_description)  %></p>
  <p><%= f.select :filter_id, filter_options_for_select(@cms_snippet.filter_id), {:label => l(:label_cms_filter)}, {:id => "text_filter_select", :onchange => "editor.setOption('mode', $('option:selected', this).data('mode'));return false;"} %></p>
  <% unless @cms_snippet.new_record? %>
  <p><%= label_tag l(:label_cms_used_in_pages) %>
  	<%= @cms_snippet.used_in_pages.map{|page| link_to page.name, edit_cms_page_path(page) }.join(', ').html_safe %>
  </p>
  <% end %>

<p id="attachments_form"><label><%= l(:label_attachment_plural) %></label><%= render :partial => 'attachments/form', :locals => {:container => @cms_snippet} %></p>

<%= text_area_tag 'cms_snippet[content]', @cms_snippet.content, :cols => 100, :rows =>  30, :class => 'wiki-edit' %>

<%= javascript_tag "editor = activateCodeMirror('cms_snippet_content', '#{@cms_snippet.filter.class.mine_type}');" %>
<%= javascript_tag "$('.contextual.page-edit').draggable();" %>

</div>


<% content_for :header_tags do %>
  <%= code_mirror_tags %>
  <%= javascript_include_tag 'redmine_cms', :plugin => 'redmine_cms'  %>
<% end %>

app/views/cms_snippets/_list.html.erb
<% if @snippets.any? %>
  <table class="list">
    <thead>
      <tr>
        <th><%= l(:label_cms_name) %></th>
        <th><%= l(:label_cms_description) %></th>
        <th style="width:10%;"> </th>
      </tr>
    </thead>
    <tbody>
      <% @snippets.each do |snippet| -%>
        <tr class="snippet <%= cycle("odd", "even") %>" id="snippet_<%= snippet.id %>">
          <td class="name"><%= link_to h(snippet.name), edit_cms_snippet_path(snippet) %></td>
          <td class="name"><%= snippet.description %></td>
          <td class="buttons">
            <%= link_to l(:label_history), cms_object_history_path(snippet, :object_type => snippet.class.name.underscore), :class => 'icon icon-history' if snippet.version > 1 %>
            <%= delete_link cms_snippet_path(snippet) if User.current.admin? %>
          </td>
        </tr>
      <% end -%>
  </tbody>
</table>
<% end %>

app/views/cms_snippets/edit.html.erb
<div class="contextual">
  <%= link_to l(:label_preview), preview_cms_snippet_path(@cms_snippet), :class => 'icon icon-preview'  %>
  <%= link_to l(:label_history), cms_object_history_path(@cms_snippet, :object_type => @cms_snippet.class.name.underscore), :class => 'icon icon-history' if @cms_snippet.version > 1 %>
  <%= link_to l(:button_export), cms_export_path(@cms_snippet.id, :object_type => @cms_snippet.class.name.underscore), :class => 'icon icon-save' %>
  <%= delete_link cms_snippet_path(@cms_snippet) if User.current.admin? %>
</div>

<h2><%= link_to l(:label_cms_snippet_plural), cms_snippets_path %> &#187; <%= @cms_snippet.name %></h2>

<%= error_messages_for 'cms_snippet' %>

<%= labelled_form_for :cms_snippet, @cms_snippet, :url => { :action => 'update', :id => @cms_snippet},
  :html => { :id => 'cms_snippet_form', :multi_part => true, :method => :put } do |f| %>

<%= render :partial => 'form', :locals => { :f => f } %>
<% if @cms_snippet.attachments.any? %>
  <fieldset><legend><%= l(:label_attachment_plural) %></legend>
    <%= link_to_cms_attachments @cms_snippet, :thumbnails => true  %>
  </fieldset><br/>
<% end %>

<%= submit_tag l(:button_save) %>
<% end %>

<% content_for :sidebar do %>
  <% render :partial => 'cms_settings/menu' %>
<% end %>

<% html_title(l(:label_cms_snippet_edit)) -%>

app/views/cms_snippets/index.html.erb
<div class="contextual">
<%= link_to l(:label_cms_snippet_new), new_cms_snippet_path, :class => 'icon icon-add' %>
<%= link_to l(:button_import), cms_import_path(:object_type => CmsSnippet.name.underscore), :class => 'icon icon-duplicate' %>
</div>

<h2><%= l(:label_cms_snippet_plural) %></h2>

<div class="autoscroll"  id="cms_snippets">
  <%= render 'list' %>
</div>

<% content_for :sidebar do %>
  <% render :partial => 'cms_settings/menu' %>
<% end %>

<% html_title(l(:label_cms_snippet_plural)) -%>

app/views/cms_snippets/new.html.erb
<h2><%= link_to l(:label_cms_snippet_plural), cms_snippets_path %> &#187; <%=l(:label_cms_snippet_new)%></h2>

<%= labelled_form_for :cms_snippet, @cms_snippet, :url => { :action => 'create', :project_id => @project },
  :html => { :id => 'layout-form', :multipart => true }  do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>

app/views/cms_snippets/preview.html.erb
<h2><%= l(:label_cms_snippet) %>: <%= link_to @cms_snippet.name, edit_cms_snippet_path(@cms_snippet) %></h2>
<%= @preview_content %>

<% content_for :header_tags do %>
  <div class="contextual page-edit">
    <% if params[:version] && @cms_snippet.version != @current_version %>
       <%= render :partial => 'cms_history/history_context_menu', :object => @cms_snippet %>
    <% else %>
      <%= link_to l(:button_edit), edit_cms_snippet_path(@cms_snippet), :class => 'icon icon-edit' %>
      <hr>
       <%= link_to l(:label_history), cms_object_history_path(@cms_snippet, :object_type => @cms_snippet.class.name.underscore), :class => 'icon icon-history'%>
      <hr>
    <% end %>
  </div>
  <%= javascript_tag "$('.contextual.page-edit').draggable();" %>
<% end if RedmineCms.allow_edit? %>