config/routes.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get "/sitemap" => "cms_site#sitemap", :defaults => {:format => :xml}

match 'site/login', :to => 'cms_site#login', :as => 'cms_login', :via => [:get, :post]
match 'site/logout', :to => 'cms_site#logout', :as => 'cms_logout', :via => [:get, :post]
match 'site/register', :to => 'cms_site#register', :via => [:get, :post], :as => 'cms_register'
match 'site/lost_password', :to => 'cms_site#lost_password', :via => [:get, :post], :as => 'cms_lost_password'
match 'site/activate', :to => 'cms_site#activate', :via => :get
match 'site/expire_cache', :to => 'cms_site#expire_cache', :via => :get, :as => 'site_expire_cache'
match 'auto_completes/cms_page_tags' => 'auto_completes#cms_page_tags', :via => :get, :as => 'auto_complete_cms_page_tags'

get "projects/:project_id/pages/:tab" => "project_tabs#show", :as => "project_tab"
get 'cms_menus/parent_menu_options' => 'cms_menus#parent_menu_options'

scope '/cms' do
  resources :cms_pages, :path => 'pages' do
    member do
     get :preview
     get :expire_cache
    end
    collection do
      get :search
    end
  end
  resources :cms_parts, :path => 'parts' do
    member do
     get :expire_cache
     get :preview
    end
  end
  resources :cms_snippets, :path => 'snippets' do
    member do
      get :preview
    end
  end
  resources :cms_variables, :path => 'variables'
  resources :cms_layouts, :path => 'layouts' do
    member do
      get :preview
    end
  end
  resources :cms_assets, :path => 'assets', :except => [:edit, :update, :show]
  resources :cms_redmine_layouts, :path => 'redmine_layouts'
  resources :cms_menus, :path => 'menus'
  resources :cms_redirects, :path => 'redirects'
  resources :cms_settings, :path => 'settings' do
    collection do
      get 'redmine_hooks'
      post 'save'
    end
  end
  get "/:object_type/:id/history" => "cms_history#history", :as => "cms_object_history"
  get "/:object_type/:id/diff" => "cms_history#diff", :as => "cms_object_diff"
  get "/:object_type/:id/annotate" => "cms_history#annotate", :as => "cms_object_annotate"
  get 'assets/:id/(:filename)', :to => 'cms_assets#show', :id => /\d+/, :filename => /.*/, :as => 'named_asset'
  get 'assets/download/:id/:filename', :to => 'cms_assets#download', :id => /\d+/, :filename => /.*/, :as => 'download_named_asset'
  get 'assets/download/:id', :to => 'cms_assets#download', :id => /\d+/, :as => 'download_cms_asset'
  get 'assets/thumbnail/:id/:size/:filename', :to => 'cms_assets#thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+|\d+x\d+/, :as => 'cms_thumbnail'
  get 'assets/timelink/:id/:timestamp/:key/:filename', :to => 'cms_assets#timelink', :id => /\d+/, :filename => /.*/, :timestamp => /\d+/, :key => /([0-9a-f]{32})/, :as => 'cms_timelink'
  get 'assets/edit', :to => 'cms_assets#edit', :as => :cms_assets_edit
  post 'assets', :to => 'cms_assets#update', :as => :cms_assets_update

  # Export
  get 'exports/:object_type/:id(.:format)' => 'cms_exports#new', :as => :cms_export
  post 'exports/:object_type/:id' => 'cms_exports#create'
  get 'exports/website' => 'cms_exports#website', :as => :cms_export_website
  post 'exports/website' => 'cms_exports#website'

  # Import
  get 'imports/website' => 'cms_imports#website', :as => :cms_import_website
  post 'imports/website' => 'cms_imports#website'
  get 'imports/:object_type' => 'cms_imports#new', :as => :cms_import
  post 'imports/:object_type' => 'cms_imports#create'

  # Voting
  get 'vote/:id' => 'cms_votes#vote', :as => :cms_page_vote
  resources :cms_page_queries
end

get 'attachments/thumbnail/:id(/:size)/:filename', :controller => 'attachments', :action => 'thumbnail', :id => /\d+/, :filename => /.*/, :size => /\d+/
get 'pages/:page_id/parts/*name' => 'cms_parts#show', :as => "show_site_part"

get 'pages/*path' => 'cms_pages#show', :as => "show_site_page"

app/models/cms_layout.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsLayout < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes
  include RedmineCms::Filterable

  has_many :pages, class_name: 'CmsPage', foreign_key: 'layout_id', dependent: :nullify

  after_commit :expire_pages_cache

  acts_as_attachable_cms
  acts_as_versionable_cms

  validates_presence_of :name, :content

  attr_protected :id if ActiveRecord::VERSION::MAJOR <= 4
  safe_attributes 'name',
                  'content',
                  'content_type',
                  'filter_id'

  def expire_pages_cache
    pages.each(&:expire_cache)
  end
end

app/controllers/cms_layouts_controller.rb
# This file is a part of Redmin CMS (redmine_cms) plugin,
# CMS plugin for redmine
#
# Copyright (C) 2011-2023 RedmineUP
# http://www.redmineup.com/
#
# redmine_cms is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_cms is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_cms.  If not, see <http://www.gnu.org/licenses/>.

class CmsLayoutsController < ApplicationController
  unloadable
  before_action :authorize_edit
  before_action :find_layout, :except => [:index, :new, :create]

  helper :attachments
  helper :cms

  def index
    @cms_layouts = CmsLayout.order(:name)
  end

  def new
    @cms_layout = CmsLayout.new
    @cms_layout.copy_from(params[:copy_from]) if params[:copy_from]
  end

  def edit
    @current_version = @cms_layout.set_content_from_version(params[:version]) if params[:version]
  end

  def show
    @current_version = @cms_layout.set_content_from_version(params[:version]) if params[:version]
    @page = CmsPage.new(:content => 'Empty content', :layout => @cms_layout)
    render((Rails.version < '5.1' ? :text : :plain) => @page.process(self), :layout => false)
  end

  def preview
    @current_version = @cms_layout.set_content_from_version(params[:version]) if params[:version]
    @cms_object = @cms_layout
    render :template => 'cms_pages/preview', :layout => 'cms_preview'
  end

  def update
    @cms_layout.safe_attributes = params[:cms_layout]
    @cms_layout.save_attachments(params[:attachments])
    if @cms_layout.save
      render_attachment_warning_if_needed(@cms_layout)
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => 'edit', :id => @cms_layout
    else
      render :action => 'edit'
    end
  end

  def create
    @cms_layout = CmsLayout.new
    @cms_layout.safe_attributes = params[:cms_layout]
    @cms_layout.save_attachments(params[:attachments])
    if @cms_layout.save
      render_attachment_warning_if_needed(@cms_layout)
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'edit', :id => @cms_layout
    else
      render :action => 'new'
    end
  end

  def destroy
    if params[:version]
      version = @cms_layout.versions.where(:version => params[:version]).first
      if version.current_version?
        flash[:warning] = l(:label_cms_version_cannot_destroy_current)
      else
        version.destroy
      end
      redirect_to cms_object_history_path(@cms_layout, :object_type => @cms_layout.class.name.underscore)
    else
      @cms_layout.destroy
      redirect_to :controller => 'cms_layouts', :action => 'index'
    end
  end

  private

  def find_layout
    @cms_layout = CmsLayout.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize_edit
    deny_access unless RedmineCms.allow_edit?
  end
end

app/views/cms_layouts/_form.html.erb
<%= error_messages_for 'cms_layout' %>

<div class="box tabular">

  <div class="splitcontent">
    <div class="splitcontentleft">
      <p><%= f.text_field :name, :size => 30, :required => true, :label => l(:label_cms_name)  %></p>
    </div>
    <div class="splitcontentright">
      <p><%= f.text_field :content_type, :label => l(:label_cms_content_type) %></p>
    </div>
  </div>



<p id="attachments_form"><label><%= l(:label_attachment_plural) %></label><%= render :partial => 'attachments/form', :locals => {:container => @cms_layout} %></p>

<%= text_area_tag 'cms_layout[content]', @cms_layout.content, :cols => 100, :rows =>  30, :class => 'wiki-edit' %>

<%= javascript_tag "editor = activateCodeMirror('cms_layout_content');" %>
<%= javascript_tag "$('.contextual.page-edit').draggable();" %>

</div>


<% content_for :header_tags do %>
  <%= code_mirror_tags %>
  <%= javascript_include_tag 'redmine_cms', :plugin => 'redmine_cms'  %>
<% end %>

app/views/cms_layouts/edit.html.erb
<div class="contextual">
  <%= link_to l(:label_preview), preview_cms_layout_path(@cms_layout), :class => 'icon icon-preview'  %>
  <%= link_to l(:label_history), cms_object_history_path(@cms_layout, :object_type => @cms_layout.class.name.underscore), :class => 'icon icon-history' if @cms_layout.version > 1 %>
  <%= link_to l(:button_export), cms_export_path(@cms_layout.id, :object_type => @cms_layout.class.name.underscore), :class => 'icon icon-save' %>
  <%= link_to l(:button_delete), cms_layout_path(@cms_layout), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
</div>

<h2><%= link_to l(:label_cms_layout_plural), cms_layouts_path %> &#187; <%= @cms_layout.name %></h2>

<%= error_messages_for 'cms_layout' %>

<%= labelled_form_for :cms_layout, @cms_layout, :url => { :action => 'update', :id => @cms_layout},
  :html => { :id => 'cms_layout_form', :multi_part => true, :method => :put } do |f| %>

  <%= render :partial => 'form', :locals => { :f => f } %>
<% if @cms_layout.attachments.any? %>
  <fieldset><legend><%= l(:label_attachment_plural) %></legend>
    <%= link_to_cms_attachments @cms_layout, :thumbnails => true  %>
  </fieldset><br/>
<% end %>

<%= submit_tag l(:button_save) %>
<% end %>

<% content_for :sidebar do %>
  <% render :partial => 'cms_settings/menu' %>
<% end %>

<% html_title(@cms_layout.name) -%>

app/views/cms_layouts/index.html.erb
<div class="contextual">
<%= link_to l(:label_cms_layout_new), new_cms_layout_path, :class => 'icon icon-add' %>
<%= link_to l(:button_import), cms_import_path(:object_type => CmsLayout.name.underscore), :class => 'icon icon-duplicate' %>
</div>

<h2><%=l(:label_cms_layout_plural)%></h2>

<div class="autoscroll">
<% if @cms_layouts.any? %>
  <table class="list">
    <thead>
      <tr>
        <th><%= l(:label_cms_name) %></th>
        <th><%= l(:label_cms_content_type) %></th>
        <th style="width:10%;"> </th>
      </tr>
    </thead>
    <tbody>
      <% @cms_layouts.each do |cms_layout| -%>
        <tr class="cms_layout <%= cycle("odd", "even") %>" id="layout_<%= cms_layout.id %>">
          <td class="name"><%= link_to h(cms_layout.name), edit_cms_layout_path(cms_layout) %></td>
          <td class="type"><%= cms_layout.content_type.blank? ? "text/html" : cms_layout.content_type  %></td>
          <td class="buttons">
            <%= link_to l(:label_history), cms_object_history_path(cms_layout, :object_type => cms_layout.class.name.underscore), :class => 'icon icon-history' if cms_layout.version > 1 %>
            <%= delete_link cms_layout_path(cms_layout) %>
          </td>
        </tr>
      <% end -%>
  </tbody>
</table>
<% end %>
</div>

<% content_for :sidebar do %>
  <% render :partial => 'cms_settings/menu' %>
<% end %>

<% html_title(l(:label_cms_layout_plural)) -%>

app/views/cms_layouts/new.html.erb
<h2><%= link_to l(:label_cms_layout_plural), cms_layouts_path %> &#187; <%=l(:label_cms_layout_new)%></h2>

<%= labelled_form_for :cms_layout, @cms_layout, :url => { :action => 'create', :project_id => @project },
  :html => { :id => 'layout-form', :multipart => true }  do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_create) %>
<% end %>

<% html_title(l(:label_cms_layout_new)) -%>